development:
  page:
    home:
      hotels: ['pullman-bordeaux-lac', 'hotel-agua-escondida', 'gioberti-hotel']

test:
  page:
    home:
      hotels: ['pullman-bordeaux-lac', 'hotel-agua-escondida', 'gioberti-hotel']

production:
  page:
    home:
      hotels: ['hotel-arenal-bilbao', 'the-st-regis-san-francisco', 'miniattico']
